name: music_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  flutter_screenutil: ^5.9.3

  flutter_bloc: ^9.1.1
  test: ^1.25.15
  bloc_test: ^10.0.0
  equatable: ^2.0.7
  connectivity_plus: ^6.1.5
  dio: ^5.9.0
  just_audio: ^0.10.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
  - lib/assets/
